# Base configuration for Modern SfM Pipeline
defaults:
  - _self_

# Device configuration
device: cuda
precision: float32

# Feature extraction
feature_extractor:
  type: "lightglue"  # Options: lightglue, loftr, disk
  max_keypoints: 8192  # Increased for more features before spatial filtering
  detection_threshold: 0.01  # Very sensitive detection to get more candidates
  nms_radius: 2  # Reduced NMS radius to allow more features
  # Multi-scale feature extraction parameters
  multi_scale: true
  scales: [1.0, 0.8, 0.6]  # Closer scales for better coverage
  # Spatial distribution parameters
  spatial_grid: 16  # 16x16 grid for finer spatial control
  features_per_cell: 32  # Fewer per cell but more cells = better distribution
  # Force spatial distribution even with fewer features
  min_features_per_cell: 8  # Minimum features per cell
  enforce_spatial_distribution: true  # Always apply spatial filtering

# Feature matching
feature_matching:
  matcher_type: "lightglue"  # Options: lightglue, loftr, superglue
  match_threshold: 0.30  # Balanced threshold for quality vs quantity
  max_matches: 3000  # More matches for better coverage
  cross_check: true
  # Enhanced filtering parameters
  confidence_weighted_filtering: true  # Use confidence in geometric filtering
  multi_model_ransac: true  # Try both fundamental matrix and homography
  adaptive_thresholds: true  # Adapt RANSAC thresholds based on match quality

# Pose estimation
pose_estimation:
  method: "colmap"  # Options: colmap, essential_matrix, pnp
  ransac:
    confidence: 0.9999
    max_iterations: 10000
    threshold: 1.0

# Bundle adjustment
bundle_adjustment:
  max_iterations: 200
  function_tolerance: 1e-8
  gradient_tolerance: 1e-12
  parameter_tolerance: 1e-10
  # Robust loss parameters
  huber_delta: 2.0  # Higher threshold for initial convergence
  use_huber_loss: true
  # Optimization settings
  learning_rate: 1e-3  # Higher learning rate for faster convergence
  optimizer: "adam"  # Options: adam, lbfgs, sgd
  optimize_intrinsics: false
  # Quality control
  outlier_threshold: 4.0  # pixels - more permissive initially
  min_inlier_ratio: 0.1   # Lower threshold to start optimization

# Reconstruction
reconstruction:
  min_triangulation_angle: 2.0  # degrees
  max_reprojection_error: 4.0   # pixels
  min_track_length: 2
  max_track_length: 50

# Visualization
visualization:
  point_size: 2.0
  camera_size: 0.1
  save_intermediate: true

# I/O
io:
  image_extensions: [".jpg", ".jpeg", ".png", ".tiff", ".bmp"]
  max_image_size: 1024
  output_format: "ply"  # Options: ply, obj, colmap
