# Textured plane scene configuration for synthetic data generation

# Scene configuration
scene:
  type: "textured_plane"
  size: 3.0
  position: [0.0, 0.0, 0.0]
  texture_scale: 0.15  # Dense texture grid

# Camera trajectory configuration
cameras:
  trajectory: "arc"  # Arc trajectory for planar scenes
  num_cameras: 6
  radius: 3.0
  height: 1.0
  look_at: [0.0, 0.0, 0.0]

  # Camera intrinsics
  intrinsics:
    focal_length: 600.0
    image_size: [640, 480]
    principal_point: [320.0, 240.0]

# Rendering configuration
rendering:
  lighting: "uniform"
  background: "gray"
  noise_level: 0.0
  anti_aliasing: true

# Output configuration
output:
  dataset_name: "textured_plane"
  base_path: "data/synthetic"